name: PEconomy
main: ru.soknight.peconomy.PEconomy
author: SoKnight
version: ${project.version}
depend: [SKLibrary]
softdepend: [PlaceholderAPI, Vault]
load: startup
api-version: 1.13
description: ${project.description}

commands:
  peconomy:
    aliases: [eco, economy, peco]
    description: Main plugin command
    usage: /peconomy help
  balance:
    aliases: [bal, money]
    description: See your or other player's balance
    usage: /balance [player]
  pay:
    aliases: [transfer]
    description: Transfer money to other wallet
    usage: /pay <player> <amount> <currency>

permissions:
  # /peco help
  peco.command.help:
    description: Allows to see plugin commands manual
    default: true

  # /peco reload
  peco.command.reload:
    description: Allows to reload plugin configurations
    default: op

  # +---------------+
  # |               |
  # |    GENERAL    |
  # |               |
  # +---------------+

  # /peco history
  peco.command.history:
    description: Allows to see own transactions history
    default: true

  # /peco history [player]
  peco.command.history.other:
    description: Allows to see transactions history of other player
    default: op
    children:
      peco.command.history: true

  # /peco info
  peco.command.info:
    description: Allows to see info about own transaction
    default: true

  # /peco info [player]
  peco.command.info.other:
    description: Allows to see info about transaction of other player
    default: op
    children:
      peco.command.info: true

  # /peco add <player> <amount> <currency>
  peco.command.add:
    description: Allows to add an amount to player's currency wallet
    default: op

  # /peco set <player> <amount> <currency>
  peco.command.set:
    description: Allows to change player's currency wallet balance
    default: op

  # /peco reset <player> <currency>
  peco.command.reset:
    description: Allows to reset player's currency wallet balance
    default: op

  # /peco take <player> <amount> <currency>
  peco.command.take:
    description: Allows to take an amount from player's currency wallet
    default: op

  # /peco convert <amount> <from> <to>
  peco.command.convert:
    description: Allows to convert funds from first currency to second currency
    default: true

  # /peco convert <amount> <from> <to> [player]
  peco.command.convert.other:
    description: Allows to convert funds from first currency to second currency on other player's wallet
    default: op
    children:
      peco.command.convert: true

  # /balance
  peco.command.balance:
    description: Allows to see own balances
    default: true

  # /balance [player]
  peco.command.balance.other:
    description: Allows to see balances of other player
    default: op
    children:
      peco.command.balance: true

  # /pay <player> <amount> <currency>
  peco.command.pay:
    description: Allows to transfer money to other player
    default: true

  # +------------+
  # |            |
  # |    MISC    |
  # |            |
  # +------------+

  # Allows to see hidden by default transaction source
  peco.transaction.sourcespy:
    description: Allows to see hidden by default transaction source
    default: op